-- 为 knowledge_articles 添加更多字段
ALTER TABLE knowledge_articles
ADD COLUMN IF NOT EXISTS author TEXT,
ADD COLUMN IF NOT EXISTS digest TEXT,
ADD COLUMN IF NOT EXISTS ip_wording TEXT,
ADD COLUMN IF NOT EXISTS item_show_type INTEGER,
ADD COLUMN IF NOT EXISTS real_item_show_type INTEGER,
ADD COLUMN IF NOT EXISTS copyright_stat INTEGER,
ADD COLUMN IF NOT EXISTS idx INTEGER,
ADD COLUMN IF NOT EXISTS msg_daily_idx INTEGER,
ADD COLUMN IF NOT EXISTS create_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS alias TEXT,
ADD COLUMN IF NOT EXISTS video_page_infos JSONB,
ADD COLUMN IF NOT EXISTS source_url TEXT;

-- 为 koc_sources 添加更多字段
ALTER TABLE koc_sources
ADD COLUMN IF NOT EXISTS signature TEXT,
ADD COLUMN IF NOT EXISTS qrcode TEXT,
ADD COLUMN IF NOT EXISTS customer_type TEXT;
